services:
  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./uploads:/opt/app/uploads
      - ./output:/opt/app/output
    env_file:
      - .env
    restart: unless-stopped
