services:
  # Vitalis Core - Library tests only
  vitalis-core:
    build:
      context: .
      dockerfile: docker/Dockerfile.core
    volumes:
      - ./vitalis-core:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
    working_dir: /workspace
    environment:
      - RUST_LOG=debug
      - CARGO_HOME=/usr/local/cargo
    command: cargo test

  # Web Frontend (Vite dev server) - standalone
  web-frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.tauri
    volumes:
      - .:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
      - node-modules-cache:/workspace/vitalis-app/node_modules
    working_dir: /workspace/vitalis-app
    environment:
      - RUST_LOG=debug
      - CARGO_HOME=/usr/local/cargo
      - VITE_HMR_PORT=1420
      - VITE_HMR_HOST=web-frontend
    ports:
      - "1420:1420" # Vite dev server
      - "3000:3000" # Alternative port
    command: npm run dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1420" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

  # Test Services
  test-rust:
    build:
      context: .
      dockerfile: docker/Dockerfile.core
    volumes:
      - ./vitalis-core:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
    working_dir: /workspace
    environment:
      - RUST_LOG=info
      - CARGO_HOME=/usr/local/cargo
    command: cargo test
    profiles: [ "test" ]

  # Note: Frontend tests should be run locally
  # cd vitalis-app && npm test

  # CI/CD Test Runner
  ci-test:
    build:
      context: .
      dockerfile: docker/Dockerfile.ci
    volumes:
      - .:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
      - node-modules-cache:/workspace/vitalis-app/node_modules
    working_dir: /workspace
    environment:
      - RUST_LOG=info
      - CARGO_HOME=/usr/local/cargo
      - CI=true
    command: |
      sh -c "
        echo '=== Running Rust tests ===' &&
        cargo test --workspace &&
        echo '=== Running Rust linting ===' &&
        cargo clippy --all-targets --all-features -- -D warnings &&
        cargo fmt --all -- --check &&
        echo '=== Frontend tests skipped (run locally) ==='
      "
    profiles: [ "ci" ]

volumes:
  cargo-cache:
  target-cache:
  node-modules-cache:
